import { systemConfirm } from '@/lib/systemConfirm';
'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PDFDocument } from 'pdf-lib';
import { collaboratorPdf, competencePdf } from './reimbursementPdf';

type Expense={id:string;collaborator_id:string|null;registration:string|null;collaborator_name:string;role:string|null;competence:string;description:string;amount:number;expense_on:string|null;supplier:string|null;category:string|null;reimbursement_type:string|null;field_leave_start:string|null;field_leave_end:string|null;notes:string|null;source:string};
type Person={id:string;registration:string|null;name:string;role:string|null;status:string|null};
type Receipt={id:string;competence:string;collaborator_id:string;file_name:string;storage_path:string;mime_type:string};
type Form={description:string;expense_on:string;supplier:string;category:string;amount:string;notes:string};
const empty:Form={description:'',expense_on:'',supplier:'',category:'PASSAGEM',amount:'',notes:''};
const categories=[['PASSAGEM','Passagem'],['HOSPEDAGEM','Hospedagem'],['ALIMENTACAO','Alimentação'],['COMBUSTIVEL','Combustível'],['TRANSPORTE','Transporte'],['PEDAGIO','Pedágio'],['OUTROS','Outros']];
const types=[['FOLGA_DE_CAMPO','Folga de Campo'],['INGRESSO_EMPRESA','Viagem para ingresso na empresa'],['REEMBOLSOS_EXTRAS','Reembolsos extras']];
const cash=(n:number)=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:string|null)=>v?`${v.slice(8,10)}/${v.slice(5,7)}/${v.slice(0,4)}`:'—';
const month=(v:string)=>v?new Date(`${v.slice(0,7)}-02T12:00:00Z`).toLocaleDateString('pt-BR',{timeZone:'UTC',month:'long',year:'numeric'}).toUpperCase():'—';
const upper=(v:string)=>v.toLocaleUpperCase('pt-BR');
const key=(x:{collaborator_id:string|null;registration:string|null;collaborator_name:string})=>x.collaborator_id||`REG:${x.registration||''}:${x.collaborator_name}`;
const parseAmount=(v:string)=>{const s=v.trim().replace(/\s/g,'');return Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s)};
const saveBlob=(data:Blob,name:string)=>{const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)};

export default function Reimbursements({sb,projectId,projectLabel,canCreate,canEdit,canDelete,canExport}:{sb:SupabaseClient;projectId:string;projectLabel:string;canCreate:boolean;canEdit:boolean;canDelete:boolean;canExport:boolean}){
 const [competences,setCompetences]=useState<string[]>([]),[competence,setCompetence]=useState(''),[newMonth,setNewMonth]=useState(''),[rows,setRows]=useState<Expense[]>([]),[people,setPeople]=useState<Person[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]);
 const [selected,setSelected]=useState(''),[search,setSearch]=useState(''),[type,setType]=useState(''),[leaveStart,setLeaveStart]=useState(''),[leaveEnd,setLeaveEnd]=useState('');
 const [form,setForm]=useState<Form>(empty),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const reload=useCallback(async()=>{if(!projectId)return;setLoading(true);setError('');const [c,r,p,files]=await Promise.all([
  sb.from('cx_reimbursement_competences').select('competence').eq('project_id',projectId).order('competence',{ascending:false}),
  sb.from('cx_reimbursements').select('id,collaborator_id,registration,collaborator_name,role,competence,description,amount,expense_on,supplier,category,reimbursement_type,field_leave_start,field_leave_end,notes,source').eq('project_id',projectId).order('collaborator_name').order('expense_on').limit(10000),
  sb.from('cx_collaborators').select('id,registration,name,role,status').eq('project_id',projectId).order('name').limit(10000),
  sb.from('cx_reimbursement_receipts').select('id,competence,collaborator_id,file_name,storage_path,mime_type').eq('project_id',projectId).limit(10000)
 ]);const fail=c.error||r.error||p.error||files.error;if(fail){setError(`Falha ao carregar reembolsos: ${fail.message}`);setLoading(false);return}
 const cs=[...new Set([...(c.data||[]).map(x=>x.competence),...(r.data||[]).map(x=>x.competence)])].sort().reverse();setCompetences(cs);setCompetence(old=>cs.includes(old)?old:cs[0]||'');setRows((r.data||[]) as Expense[]);setPeople((p.data||[]) as Person[]);setReceipts((files.data||[]) as Receipt[]);setLoading(false)},[sb,projectId]);
 useEffect(()=>{void reload()},[reload]);
 useEffect(()=>{setSelected('');setForm(empty);setEditing(null);setNotice('')},[projectId]);
 useEffect(()=>{if(!selected)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setSelected('')};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[selected]);
 const current=useMemo(()=>rows.filter(x=>x.competence===competence),[rows,competence]);
 const grouped=useMemo(()=>{const m=new Map<string,{key:string;id:string|null;registration:string|null;name:string;role:string|null;items:Expense[];total:number}>();for(const x of current){const k=key(x),g=m.get(k)||{key:k,id:x.collaborator_id,registration:x.registration,name:x.collaborator_name,role:x.role,items:[],total:0};g.items.push(x);g.total+=Number(x.amount||0);m.set(k,g)}return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))},[current]);
 const shown=grouped.filter(g=>`${g.name} ${g.registration||''}`.toLocaleUpperCase('pt-BR').includes(search.toLocaleUpperCase('pt-BR')));
 const person=people.find(p=>p.id===selected),group=grouped.find(g=>g.key===selected||g.id===selected),items=group?.items||[];
 const total=current.reduce((n,x)=>n+Number(x.amount||0),0);
 useEffect(()=>{const first=items.find(x=>x.reimbursement_type);setType(first?.reimbursement_type||'');setLeaveStart(first?.field_leave_start||'');setLeaveEnd(first?.field_leave_end||'');setEditing(null);setForm(empty)},[selected,competence,rows]);
 async function openCompetence(){if(!canCreate||!newMonth||busy)return;setBusy(true);setError('');const value=`${newMonth}-01`;const {error:e}=await sb.from('cx_reimbursement_competences').upsert({project_id:projectId,competence:value},{onConflict:'project_id,competence',ignoreDuplicates:true});if(e)setError(e.message);else{await reload();setCompetence(value);setNewMonth('');setNotice(`Competência ${month(value)} aberta.`)}setBusy(false)}
 async function saveHeader(){if(!canEdit||!group||!competence||!type||busy)return;if(type==='FOLGA_DE_CAMPO'&&(!leaveStart||!leaveEnd||leaveEnd<leaveStart)){setError('Informe um período de folga válido.');return}setBusy(true);setError('');const ids=items.map(x=>x.id);const {error:e}=await sb.from('cx_reimbursements').update({reimbursement_type:type,field_leave_start:type==='FOLGA_DE_CAMPO'?leaveStart:null,field_leave_end:type==='FOLGA_DE_CAMPO'?leaveEnd:null,updated_at:new Date().toISOString()}).eq('project_id',projectId).eq('competence',competence).in('id',ids);if(e)setError(e.message);else{setNotice('Dados do reembolso atualizados.');await reload()}setBusy(false)}
 async function saveExpense(){if((editing&&!canEdit||!editing&&!canCreate)||busy||!competence||!selected||(!person&&!group))return;const amount=parseAmount(form.amount);if(!form.description.trim()||!Number.isFinite(amount)||amount<=0){setError('Preencha a descrição e um valor maior que zero.');return}if(type==='FOLGA_DE_CAMPO'&&(!leaveStart||!leaveEnd||leaveEnd<leaveStart)){setError('Informe um período de folga válido.');return}setBusy(true);setError('');const original=items.find(x=>x.id===editing);const payload={description:upper(form.description.trim()),expense_on:form.expense_on||null,supplier:form.supplier.trim()?upper(form.supplier.trim()):null,category:form.category,amount,notes:form.notes.trim()?upper(form.notes.trim()):null,reimbursement_type:type||original?.reimbursement_type||null,field_leave_start:type==='FOLGA_DE_CAMPO'?leaveStart||null:original?.field_leave_start||null,field_leave_end:type==='FOLGA_DE_CAMPO'?leaveEnd||null:original?.field_leave_end||null,updated_at:new Date().toISOString()};
 const result=editing?await sb.from('cx_reimbursements').update(payload).eq('id',editing).eq('project_id',projectId):await sb.from('cx_reimbursements').insert({...payload,project_id:projectId,competence,collaborator_id:person?.id||group?.id||null,registration:person?.registration||group?.registration||null,collaborator_name:person?.name||group?.name||'',role:person?.role||group?.role||null,source:'V2'});
 if(result.error)setError(result.error.message);else{setNotice(editing?'Despesa atualizada.':'Despesa incluída.');setEditing(null);setForm(empty);await reload()}setBusy(false)}
 function editExpense(x:Expense){setSelected(key(x));setForm({description:x.description,expense_on:x.expense_on||'',supplier:x.supplier||'',category:x.category||'OUTROS',amount:Number(x.amount).toFixed(2).replace('.',','),notes:x.notes||''});setEditing(x.id);setError('')}
 async function deleteExpense(x:Expense){if(!canDelete||busy||!await systemConfirm(`Excluir a despesa ${x.description} (${cash(x.amount)})?`))return;setBusy(true);setError('');const {error:e}=await sb.from('cx_reimbursements').delete().eq('id',x.id).eq('project_id',projectId);if(e)setError(e.message);else{setNotice('Despesa excluída.');if(editing===x.id){setEditing(null);setForm(empty)}await reload()}setBusy(false)}
 function pdf(title:string,list:Expense[],name:string){if(!list.length){setError('Não há despesas nesta seleção.');return}const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text(title,105,16,{align:'center',maxWidth:184});doc.setFontSize(9);doc.text(`${projectLabel}  ·  ${month(competence)}`,105,23,{align:'center',maxWidth:185});autoTable(doc,{startY:30,head:[['COLABORADOR','DESCRIÇÃO','DATA','FORNECEDOR','VALOR']],body:list.map(x=>[x.collaborator_name,x.description,date(x.expense_on),x.supplier||'—',cash(x.amount)]),theme:'grid',styles:{fontSize:7,cellPadding:1.7,overflow:'linebreak'},headStyles:{fillColor:[245,197,24],textColor:[0,0,0],fontStyle:'bold'},columnStyles:{0:{cellWidth:39},1:{cellWidth:57},2:{cellWidth:21},3:{cellWidth:43},4:{cellWidth:28,halign:'right'}},margin:{left:11,right:11,bottom:18}});const end=(doc as jsPDF&{lastAutoTable:{finalY:number}}).lastAutoTable.finalY;if(end>260)doc.addPage();doc.setFontSize(10);doc.text(`TOTAL: ${cash(list.reduce((n,x)=>n+Number(x.amount||0),0))}`,198,Math.min(end+10,275),{align:'right'});doc.save(name)}
 async function fullPdf(){
  if(!grouped.length){setError('Não há reembolsos nesta competência.');return}
  if(busy)return;
  setBusy(true);setError('');setNotice('Preparando o PDF completo e os comprovantes…');
  try{
   const result=await PDFDocument.create();
   async function appendPdf(bytes:ArrayBuffer){const source=await PDFDocument.load(bytes);const pages=await result.copyPages(source,source.getPageIndices());pages.forEach(page=>result.addPage(page))}
   await appendPdf(competencePdf(grouped,competence).output('arraybuffer'));
   for(const g of grouped){
    await appendPdf(collaboratorPdf(g,competence).output('arraybuffer'));
    const attached=receipts.filter(r=>r.competence===competence&&r.collaborator_id===g.id);
    for(const receipt of attached){
     const {data,error:downloadError}=await sb.storage.from('cx-reimbursement-receipts').download(receipt.storage_path);
     if(downloadError||!data)throw new Error(`Não foi possível incluir ${receipt.file_name} (${g.name}): ${downloadError?.message||'arquivo indisponível'}`);
     const bytes=await data.arrayBuffer();const mime=receipt.mime_type.toLowerCase();
     if(mime==='application/pdf'||receipt.file_name.toLowerCase().endsWith('.pdf'))await appendPdf(bytes);
     else if(mime==='image/png'||mime==='image/jpeg'||mime==='image/jpg'){
      const img=mime==='image/png'?await result.embedPng(bytes):await result.embedJpg(bytes);
      const page=result.addPage([595.28,841.89]);const scale=Math.min(555/img.width,800/img.height,1);
      page.drawImage(img,{x:(595.28-img.width*scale)/2,y:(841.89-img.height*scale)/2,width:img.width*scale,height:img.height*scale});
     }else throw new Error(`Formato de comprovante não suportado: ${receipt.file_name}`);
    }
   }
   saveBlob(new Blob([new Uint8Array(await result.save())],{type:'application/pdf'}),`REEMBOLSOS_COMPLETO_${competence.slice(0,7)}.pdf`);
   setNotice('PDF completo gerado com a relação, os resumos individuais e os comprovantes.');
  }catch(cause){setNotice('');setError(cause instanceof Error?cause.message:'Falha ao gerar o PDF completo.')}
  finally{setBusy(false)}
 }
 function excel(){if(!current.length){setError('Não há despesas nesta competência.');return}const cells=[['MATRÍCULA','COLABORADOR','FUNÇÃO','DATA','DESCRIÇÃO','FORNECEDOR','CATEGORIA','TIPO','VALOR','OBSERVAÇÃO'],...current.map(x=>[x.registration||'',x.collaborator_name,x.role||'',x.expense_on||'',x.description,x.supplier||'',x.category||'',x.reimbursement_type||'',Number(x.amount).toFixed(2).replace('.',','),x.notes||''])];const csv='\uFEFF'+cells.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\r\n');saveBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),`REEMBOLSOS_${competence.slice(0,7)}.csv`)}
 async function uploadReceipt(file:File|undefined){if(!file||!canCreate||!person||!competence||busy)return;if(!['application/pdf','image/jpeg','image/png'].includes(file.type)||file.size>10485760){setError('Anexe PDF, JPG ou PNG de até 10 MB.');return}setBusy(true);setError('');const path=`${projectId}/${competence.slice(0,7)}/${person.id}/${crypto.randomUUID()}.${file.type==='application/pdf'?'pdf':file.type==='image/png'?'png':'jpg'}`;const sent=await sb.storage.from('cx-reimbursement-receipts').upload(path,file,{contentType:file.type});if(sent.error)setError(sent.error.message);else{const inserted=await sb.from('cx_reimbursement_receipts').insert({project_id:projectId,competence,collaborator_id:person.id,file_name:file.name,storage_path:path,mime_type:file.type});if(inserted.error)setError(`Arquivo enviado, mas o vínculo não foi salvo: ${inserted.error.message}`);else{setNotice('Comprovante anexado.');await reload()}}setBusy(false)}
 async function downloadReceipt(receipt:Receipt){setBusy(true);setError('');const result=await sb.storage.from('cx-reimbursement-receipts').download(receipt.storage_path);if(result.error)setError(result.error.message);else saveBlob(result.data,receipt.file_name);setBusy(false)}
 async function deleteReceipt(receipt:Receipt){if(!canDelete||busy||!await systemConfirm(`Excluir o comprovante ${receipt.file_name}?`))return;setBusy(true);setError('');const removed=await sb.storage.from('cx-reimbursement-receipts').remove([receipt.storage_path]);if(removed.error)setError(removed.error.message);else{const row=await sb.from('cx_reimbursement_receipts').delete().eq('id',receipt.id).eq('project_id',projectId);if(row.error)setError(row.error.message);else{setNotice('Comprovante excluído.');await reload()}}setBusy(false)}
 const selectPerson=(v:string)=>{setSelected(v);setError('');setNotice('')};
 const closePerson=()=>{setSelected('');setEditing(null);setForm(empty);setError('');setNotice('')};
 return <section className="cx-reimbursements"><div className="panel cx-r-head"><div><h2>Controle de Reembolsos</h2><p>Selecione a competência, escolha o colaborador e gerencie as despesas.</p></div><label>Competência<select value={competence} onChange={e=>{setCompetence(e.target.value);closePerson()}}><option value="">Selecione...</option>{competences.map(c=><option key={c} value={c}>{month(c)}</option>)}</select></label>{canCreate&&<div className="cx-r-open"><button type="button" onClick={()=>selectPerson('NEW')}>＋ LANÇAR REEMBOLSO</button><input type="month" aria-label="Nova competência" value={newMonth} onChange={e=>setNewMonth(e.target.value)}/><button type="button" disabled={!newMonth||busy} onClick={()=>void openCompetence()}>＋ Abrir competência</button></div>}</div>
 {!selected&&error&&<div className="notice" role="alert">{error}</div>}{!selected&&notice&&<div className="notice" role="status">{notice}</div>}
 <div className="cx-r-kpis"><div className="panel"><small>COMPETÊNCIA</small><strong>{month(competence)}</strong><span>Mês selecionado</span></div><div className="panel"><small>TOTAL REEMBOLSOS</small><strong>{cash(total)}</strong><span>Valor acumulado</span></div><div className="panel"><small>COLABORADORES</small><strong>{grouped.length}</strong><span>Com lançamento</span></div><div className="panel"><small>LANÇAMENTOS</small><strong>{current.length}</strong><span>Linhas de despesa</span></div></div>
 {loading?<div className="panel">Carregando Reembolsos…</div>:<>{selected&&<div className="cx-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closePerson()}}><div className="panel cx-modal cx-r-modal" role="dialog" aria-modal="true" aria-label="Detalhamento de reembolso"><div className="cx-dialog-head"><div><span className="eyebrow">{month(competence)}</span><h2>{person?.name||group?.name||'LANÇAR REEMBOLSO'}</h2></div><button type="button" className="cx-dialog-close" aria-label="Fechar detalhamento" onClick={closePerson}>×</button></div>{error&&<div className="notice" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}<div className="panel cx-r-person"><label>Colaborador<select value={selected} onChange={e=>selectPerson(e.target.value)}><option value="NEW">Selecione...</option>{people.filter(p=>!['INATIVO','DESLIGADO','ABANDONO'].includes(upper(p.status||''))||grouped.some(g=>g.id===p.id)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.registration||'SEM MATRÍCULA'}</option>)}{grouped.filter(g=>!g.id||!people.some(p=>p.id===g.id)).map(g=><option key={g.key} value={g.key}>{g.name} · {g.registration||'SEM MATRÍCULA'}</option>)}</select></label><div>{person||group?`${person?.name||group?.name} · MATRÍCULA ${person?.registration||group?.registration||'—'} · ${person?.role||group?.role||'FUNÇÃO NÃO INFORMADA'}`:'Selecione um colaborador para lançar ou consultar despesas.'}</div></div>
 {(person||group)&&<><div className="panel"><div className="cx-r-panel-head"><div><h2>Dados do reembolso</h2><p>Tipo e período referentes ao colaborador nesta competência.</p></div>{canEdit&&!!items.length&&<button type="button" disabled={busy||!type} onClick={()=>void saveHeader()}>💾 SALVAR DADOS</button>}</div><div className="cx-r-form"><label>Tipo de reembolso<select value={type} onChange={e=>setType(e.target.value)} disabled={!canEdit&&!canCreate}><option value="">SELECIONE...</option>{types.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>{type==='FOLGA_DE_CAMPO'&&<><label>Período da folga — de<input type="date" value={leaveStart} onChange={e=>setLeaveStart(e.target.value)} disabled={!canEdit&&!canCreate}/></label><label>Até<input type="date" value={leaveEnd} onChange={e=>setLeaveEnd(e.target.value)} disabled={!canEdit&&!canCreate}/></label></>}</div></div>
 {(canCreate||canEdit)&&<div className="panel"><div className="cx-r-panel-head"><div><h2>{editing?'Editar despesa':'Lançamento de despesas'}</h2><p>Informe os dados da despesa do colaborador selecionado.</p></div></div><div className="cx-r-form"><label className="wide">Descrição da despesa<input value={form.description} placeholder="Ex.: PASSAGEM RODOVIÁRIA - GOIÂNIA > CRIXÁS" onChange={e=>setForm(f=>({...f,description:upper(e.target.value)}))}/></label><label>Data<input type="date" value={form.expense_on} onChange={e=>setForm(f=>({...f,expense_on:e.target.value}))}/></label><label>Fornecedor<input value={form.supplier} onChange={e=>setForm(f=>({...f,supplier:upper(e.target.value)}))}/></label><label>Categoria<select value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))}>{form.category&&!categories.some(([v])=>v===form.category)&&<option value={form.category}>{form.category}</option>}{categories.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Valor (R$)<input inputMode="decimal" value={form.amount} placeholder="0,00" onChange={e=>setForm(f=>({...f,amount:e.target.value}))}/></label><label className="wide">Observação<input value={form.notes} onChange={e=>setForm(f=>({...f,notes:upper(e.target.value)}))}/></label></div><div className="cx-r-actions"><button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Limpar</button><button type="button" className="cx-r-primary" disabled={busy||!!editing&&!canEdit||!editing&&!canCreate} onClick={()=>void saveExpense()}>{busy?'Processando…':editing?'💾 SALVAR ALTERAÇÃO':'＋ INCLUIR'}</button></div></div>}
 <div className="panel"><div className="cx-r-panel-head"><div><h2>Comprovantes</h2><p>Arquivos restritos aos usuários com acesso aos reembolsos desta obra.</p></div>{canCreate&&person&&<label className="cx-r-upload">＋ ANEXAR PDF / IMAGEM<input type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy} onChange={e=>{void uploadReceipt(e.target.files?.[0]);e.target.value=''}}/></label>}</div><div className="cx-r-receipts">{receipts.filter(r=>r.competence===competence&&r.collaborator_id===(person?.id||group?.id)).map(r=><div key={r.id}><span>📎 {r.file_name}</span><div className="cx-r-actions"><button type="button" disabled={busy} onClick={()=>void downloadReceipt(r)}>⬇ BAIXAR</button>{canDelete&&<button type="button" disabled={busy} onClick={()=>void deleteReceipt(r)} title="Excluir comprovante">🗑</button>}</div></div>)}{!receipts.some(r=>r.competence===competence&&r.collaborator_id===(person?.id||group?.id))&&<div className="empty">Nenhum comprovante anexado.</div>}</div></div>
 <div className="panel"><div className="cx-r-panel-head"><div><h2>Despesas do colaborador</h2><p>{group?.name||person?.name} · {month(competence)}</p></div><strong>Total: {cash(items.reduce((n,x)=>n+Number(x.amount||0),0))}</strong></div><div className="cx-r-scroll"><table><thead><tr><th>Item</th><th>Descrição</th><th>Data</th><th>Fornecedor</th><th>Categoria</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{items.map((x,i)=><tr key={x.id}><td>{String(i+1).padStart(2,'0')}</td><td>{x.description}</td><td>{date(x.expense_on)}</td><td>{x.supplier||'—'}</td><td>{x.category||'—'}</td><td>{cash(x.amount)}</td><td><div className="cx-r-actions">{canEdit&&<button type="button" disabled={busy} onClick={()=>editExpense(x)}>✏️ EDITAR</button>}{canDelete&&<button type="button" disabled={busy} onClick={()=>void deleteExpense(x)} title="Excluir despesa">🗑</button>}</div></td></tr>)}</tbody></table>{!items.length&&<div className="empty">Nenhuma despesa deste colaborador nesta competência.</div>}</div></div></>}</div></div>}
 <div className="panel"><div className="cx-r-panel-head"><div><h2>Reembolsos cadastrados</h2><p>Consolidado por colaborador na competência selecionada.</p></div>{canExport&&<div className="cx-r-actions"><span>RESUMO DA COMPETÊNCIA</span><button type="button" onClick={()=>{if(!grouped.length){setError('Não há reembolsos nesta competência.');return}competencePdf(grouped,competence).save(`REEMBOLSOS_${competence.slice(0,7)}.pdf`)}}>PDF</button><button type="button" onClick={excel}>EXCEL (CSV)</button><button type="button" disabled={busy} onClick={()=>void fullPdf()}>{busy?'GERANDO…':'PDF COMPLETO'}</button></div>}</div><input className="cx-r-search" value={search} placeholder="Buscar colaborador ou matrícula" onChange={e=>setSearch(e.target.value)} aria-label="Buscar colaborador ou matrícula"/><div className="cx-r-scroll"><table><thead><tr><th>Colaborador</th><th>Função</th><th>Qtd. despesas</th><th>Total</th><th>Ações</th></tr></thead><tbody>{shown.map(g=><tr key={g.key}><td>{g.registration||'—'} · <button type="button" className="cx-r-person-link" onClick={()=>selectPerson(g.key)} title={`Ver detalhamento de ${g.name}`}>{g.name}</button></td><td>{g.role||'—'}</td><td>{g.items.length}</td><td>{cash(g.total)}</td><td><div className="cx-r-actions">{canExport&&<button type="button" onClick={()=>collaboratorPdf(g,competence).save(`REEMBOLSO_${g.name.replace(/[^A-Za-z0-9]+/g,'_')}_${competence.slice(0,7)}.pdf`)}>📄 PDF</button>}</div></td></tr>)}</tbody></table>{!shown.length&&<div className="empty">Nenhum reembolso nesta competência.</div>}</div></div></>}
 </section>
}
