import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export type PrintLeave={id:string;collaborator_id:string|null;registration:string|null;collaborator_name:string;competence:string;starts_on:string|null;ends_on:string|null;returns_on:string|null;days:number|null;distance_km:number|null;reimbursement_amount?:number|null;city:string|null;state:string|null;origin_city:string|null;origin_state:string|null};
export type PrintPerson={id:string;registration:string|null;name:string;role:string|null;status:string|null;contract_type:string|null;hired_on:string|null;travel_state:string|null;travel_city:string|null;distance_km:number|null;entitled_to_leave:string|null;uses_lodging:string|null;sector?:string|null;team?:string|null;department?:string|null};
export type PrintExpense={field_leave_id:string;description:string;amount:number;expense_type:string|null;segment_number:number|null;origin_city:string|null;origin_state:string|null;destination_city:string|null;destination_state:string|null};
export type PrintHistory={collaborator_id:string|null;starts_on:string;ends_on:string|null;source:string};

const fmt=(v:string|null|undefined)=>v?`${v.slice(8,10)}/${v.slice(5,7)}/${v.slice(0,4)}`:'—';
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const addMonths=(iso:string,n:number)=>{const [y,m,d]=iso.slice(0,10).split('-').map(Number);if(!y||!m||!d)return '';const x=new Date(Date.UTC(y,m-1+n,1,12));const last=new Date(Date.UTC(x.getUTCFullYear(),x.getUTCMonth()+1,0,12)).getUTCDate();x.setUTCDate(Math.min(d,last));return x.toISOString().slice(0,10)};
const addDays=(iso:string,n:number)=>{const x=new Date(`${iso}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const fifth=(iso:string,n:number)=>{const first=addMonths(iso.slice(0,7)+'-01',n);if(!first)return '';const [y,m]=first.split('-').map(Number);let count=0;for(let i=1;i<16;i++){const d=new Date(Date.UTC(y,m-1,i,12));if(d.getUTCDay()!==0&&d.getUTCDay()!==6&&++count===5)return d.toISOString().slice(0,10)}return ''};
const rule=(km:number)=>km>1000?{months:6,days:7,period:'6x6'}:km>500?{months:3,days:5,period:'3x3'}:{months:2,days:3,period:'2x2'};
const safe=(v:string)=>v.replace(/[^A-Za-z0-9À-ÿ]+/g,'_');
async function logo(){const r=await fetch('/ccl-logo-folga.png');if(!r.ok)throw new Error('Logo da CCL não localizado.');const b=await r.blob();return new Promise<string>((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.onerror=reject;fr.readAsDataURL(b)})}
function download(data:Uint8Array,name:string){const file=new Uint8Array(data.length);file.set(data);const url=URL.createObjectURL(new Blob([file],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}

export async function term(l:PrintLeave,p:PrintPerson|undefined,projectLabel:string,returnBytes=false){
 if(!l.city||!l.state||!l.starts_on||!l.ends_on||!l.distance_km)throw new Error('Confira período, cidade, UF e distância antes de gerar o termo.');
 const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),PW=doc.internal.pageSize.getWidth(),ML=27,MR=24,CW=PW-ML-MR;let y=35;
 doc.addImage(await logo(),'PNG',ML,12,36,18);doc.setTextColor(30);doc.setFont('helvetica','bold');doc.setFontSize(12.2);doc.text('COMUNICAÇÃO E CONCESSÃO DE FOLGA DE CAMPO',PW/2,y,{align:'center'});y+=22;
 const line=(label:string,value:string,bold=false)=>{doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.setTextColor(55);doc.text(label,ML,y);const x=ML+doc.getTextWidth(label)+1.2;doc.setFont('helvetica',bold?'bold':'normal');doc.setTextColor(65);const lines=doc.splitTextToSize(value||'—',PW-MR-x);doc.text(lines,x,y);y+=Math.max(6,lines.length*5)};
 line('Empregado(a):',l.collaborator_name.toUpperCase());line('Matrícula:',l.registration||p?.registration||'—');line('Obra/Unidade:',projectLabel);line('Cargo:',(p?.role||'—').toUpperCase());y+=4;line('Cidade Residência Informado:',`${l.city}-${l.state}`.toUpperCase());y+=4;line('Distância da Obra:',`${Number(l.distance_km).toLocaleString('pt-BR')}km`);y+=4;
 const days=l.days||Math.round((Date.parse(l.ends_on)-Date.parse(l.starts_on))/86400000)+1,words:Record<number,string>={1:'um',2:'dois',3:'três',4:'quatro',5:'cinco',6:'seis',7:'sete',8:'oito',9:'nove',10:'dez'};
 doc.setFont('helvetica','normal');doc.setFontSize(10.4);doc.setTextColor(70);
 const message=`Nos termos da Cláusula Vigésima Sexta da Convenção Coletiva de Trabalho vigente, comunicamos a concessão de ${String(days).padStart(2,'0')} (${words[days]||String(days)}) dias corridos de Folga de Campo para Visita Familiar, em razão de residência superior a 500 km do local da obra.`;
 const lines=doc.splitTextToSize(message,CW);doc.text(lines,ML,y,{align:'justify',maxWidth:CW});y+=lines.length*5+6;
 doc.text('Período da Folga:',ML,y);y+=6;line('Início:',fmt(l.starts_on));y+=3;line('Fim:',fmt(l.ends_on));y+=7;line('Retorno ao Trabalho:',fmt(l.returns_on||addDays(l.ends_on,1)),true);y+=5;
 doc.setFont('helvetica','normal');doc.setFontSize(10.4);const declaration='O empregado declara estar ciente das datas acima informadas e compromete-se a retornar às suas atividades na data estipulada.';const dl=doc.splitTextToSize(declaration,CW);doc.text(dl,ML,y);y+=dl.length*5+14;
 const today=new Date(),place=`Crixás - GO, ${String(today.getDate()).padStart(2,'0')} de ${months[today.getMonth()]} de ${today.getFullYear()}`;doc.text(place,ML,y);y+=31;
 const cx=PW/2;doc.setDrawColor(90);doc.setLineWidth(.25);doc.line(cx-31,y,cx+31,y);doc.setFontSize(9.5);doc.text('Assinatura do Empregado(a)',cx,y+5,{align:'center'});y+=29;doc.line(cx-31,y,cx+31,y);doc.text('Gestor da Obra',cx,y+5,{align:'center'});doc.text('CONSTRUTORA CENTRO LESTE SA',cx,y+11,{align:'center'});
 if(returnBytes)return new Uint8Array(doc.output('arraybuffer'));doc.save(`Termo_Folga_de_Campo_${safe(l.collaborator_name)}_${l.competence.slice(0,7)}.pdf`);
}

export async function termsBatch(leaves:PrintLeave[],people:PrintPerson[],projectLabel:string){if(!leaves.length)throw new Error('Não há folgas nesta competência.');const pdf=await PDFDocument.create();for(const leave of leaves){const raw=await term(leave,people.find(p=>p.id===leave.collaborator_id),projectLabel,true);if(!(raw instanceof Uint8Array))continue;const source=await PDFDocument.load(raw);for(const page of await pdf.copyPages(source,source.getPageIndices()))pdf.addPage(page)}download(await pdf.save(),`TODOS_OS_TERMOS_FOLGA_DE_CAMPO_${leaves[0].competence.slice(0,7)}.pdf`)}

// Os PDFs do v1 já possuem um cabeçalho que pode sair das margens. Preservamos
// o corpo e as páginas seguintes; apenas o cabeçalho da primeira página é refeito.
export async function fitLegacySimulation(l:PrintLeave,original:Blob):Promise<Blob>{
 const source=await PDFDocument.load(await original.arrayBuffer()),out=await PDFDocument.create();
 const first=source.getPage(0),{width:W,height:H}=first.getSize();
 // O primeiro print pode começar logo após as datas. Reserve somente 80 pt
 // para retirar o cabeçalho antigo, deslocando todo o restante para baixo.
 const margin=32,oldHeader=80,body=await out.embedPage(first,{left:0,bottom:0,right:W,top:H-oldHeader});
 const page=out.addPage([W,H]),font=await out.embedFont(StandardFonts.HelveticaBold),size=12,lineHeight=16;
 const wrap=(value:string)=>{const lines:string[]=[];let current='';for(const word of value.split(/\s+/)){const candidate=current?`${current} ${word}`:word;if(font.widthOfTextAtSize(candidate,size)>W-2*margin&&current){lines.push(current);current=word}else current=candidate}if(current)lines.push(current);return lines};
 const title=wrap(`SIMULAÇÃO DE VALORES DE PASSAGEM - ${l.collaborator_name.toUpperCase()}`);
 const meal=Number(l.distance_km||0)>1000?190:110;
 const route=wrap(`${l.origin_city||'CRIXÁS'}-${l.origin_state||'GO'} > ${l.city||'—'}-${l.state||'—'} - ${Number(l.distance_km||0).toLocaleString('pt-BR')}KM   /   REFEIÇÃO IDA E VOLTA R$ ${money(meal)}`.toUpperCase());
 const dates=[`INÍCIO: ${fmt(l.starts_on)}`,`FIM: ${fmt(l.ends_on)}`,`RETORNO TRABALHO: ${fmt(l.returns_on)}`];
 const dateWidths=dates.map(value=>font.widthOfTextAtSize(value,size));
 const fits=dateWidths[0]+dateWidths[1]+dateWidths[2]+36<=W-2*margin;
 const headerHeight=Math.max(oldHeader,24+title.length*lineHeight+7+route.length*lineHeight+8+(fits?0:lineHeight)+27);
 const bodyHeight=H-oldHeader,scale=Math.min(1,(H-headerHeight)/bodyHeight);
 if(scale<=0)throw new Error('O cabeçalho não cabe na página da simulação.');
 page.drawPage(body,{x:(W-W*scale)/2,y:0,width:W*scale,height:bodyHeight*scale});
 page.drawRectangle({x:0,y:H-headerHeight,width:W,height:headerHeight,color:rgb(1,1,1)});
 const center=(line:string,y:number)=>page.drawText(line,{x:(W-font.widthOfTextAtSize(line,size))/2,y,size,font,color:rgb(0,0,0)});
 let y=H-24;for(const line of title){center(line,y);y-=lineHeight}y-=7;
 for(const line of route){center(line,y);y-=lineHeight}y-=8;
 if(fits){page.drawText(dates[0],{x:margin,y,size,font});center(dates[1],y);page.drawText(dates[2],{x:W-margin-dateWidths[2],y,size,font})}
 else{center(`${dates[0]}   /   ${dates[1]}`,y);y-=lineHeight;center(dates[2],y)}
 if(source.getPageCount()>1){const other=await out.copyPages(source,Array.from({length:source.getPageCount()-1},(_,i)=>i+1));other.forEach(p=>out.addPage(p))}
 const bytes=await out.save();return new Blob([new Uint8Array(bytes)],{type:'application/pdf'});
}

export async function simulation(l:PrintLeave,imageBlob:Blob,returnBytes=false){
 const doc=new jsPDF({orientation:'portrait',unit:'pt',format:'a4',compress:true}),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),M=32;
 const km=Number(l.distance_km||0),meal=km>1000?190:110;
 doc.setTextColor(10,10,10);doc.setFont('helvetica','bold');doc.setFontSize(12);
 let y=24;const lineHeight=16;
 const centered=(value:string)=>{const lines=doc.splitTextToSize(value.toUpperCase(),W-M*2) as string[];for(const line of lines){doc.text(line,W/2,y,{align:'center'});y+=lineHeight}};
 centered(`SIMULAÇÃO DE VALORES DE PASSAGEM - ${l.collaborator_name}`);y+=7;
 centered(`${l.origin_city||'CRIXÁS'}-${l.origin_state||'GO'} > ${l.city||'—'}-${l.state||'—'} - ${km?km.toLocaleString('pt-BR')+'KM':'KM NÃO INFORMADO'}   /   REFEIÇÃO IDA E VOLTA R$ ${money(meal)}`);y+=8;
 const dates=[`INÍCIO: ${fmt(l.starts_on)}`,`FIM: ${fmt(l.ends_on)}`,`RETORNO TRABALHO: ${fmt(l.returns_on)}`];
 if(dates.reduce((sum,value)=>sum+doc.getTextWidth(value),0)+36<=W-2*M){doc.text(dates[0],M,y);doc.text(dates[1],W/2,y,{align:'center'});doc.text(dates[2],W-M,y,{align:'right'})}
 else{centered(`${dates[0]}   /   ${dates[1]}`);centered(dates[2]);y-=lineHeight}
 y+=28;
 const url=URL.createObjectURL(imageBlob);
 try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=reject;img.src=url});const data=await new Promise<string>((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.onerror=reject;fr.readAsDataURL(imageBlob)});
 let imageY=y;let ratio=Math.min((W-M*2)/img.width,(H-imageY-M)/img.height);
 if(ratio<=0){doc.addPage();imageY=M;ratio=Math.min((W-M*2)/img.width,(H-imageY-M)/img.height)}
 const w=img.width*ratio,h=img.height*ratio;doc.addImage(data,imageBlob.type==='image/png'?'PNG':'JPEG',(W-w)/2,imageY,w,h,undefined,'FAST');
 if(returnBytes)return new Uint8Array(doc.output('arraybuffer'));
 doc.save(`SIMULACAO_PASSAGENS_${safe(l.collaborator_name)}_${l.competence.slice(0,7)}.pdf`);
 }finally{URL.revokeObjectURL(url)}
}

export function detailing(l:PrintLeave,person:PrintPerson|undefined,expenses:PrintExpense[],returnBytes=false){if(!expenses.length)throw new Error('Não há despesas para este colaborador.');expenses=[...expenses].sort((a,b)=>{const aRoute=(a.expense_type||'').startsWith('PASSAGEM'),bRoute=(b.expense_type||'').startsWith('PASSAGEM');return Number(bRoute)-Number(aRoute)||(aRoute&&bRoute?(a.segment_number??999)-(b.segment_number??999):0)});const doc=new jsPDF({orientation:'portrait',unit:'pt',format:'a4'}),W=doc.internal.pageSize.getWidth(),left=10,fullW=W-20,peach:[number,number,number]=[244,163,64];doc.setDrawColor(10);doc.setLineWidth(.3);doc.setFillColor(...peach);doc.rect(left,30,fullW,48,'FD');doc.setFont('helvetica','bold');doc.setFontSize(15.5);doc.text('DETALHAMENTO DE DESPESAS - FOLGA DE CAMPO',W/2,60,{align:'center'});doc.setFontSize(9);const [yy,mm]=l.competence.split('-').map(Number);doc.text(`MÊS DE COMPETÊNCIA: ${months[mm-1].toUpperCase()} DE ${yy}`,W/2,94,{align:'center'});
 const infoY=107,infoH=34,labelNomeW=48,labelFuncW=58,nomeW=Math.round(fullW*.49),funcW=fullW-labelNomeW-labelFuncW-nomeW,x0=left,x1=x0+labelNomeW,x2=x1+nomeW,x3=x2+labelFuncW;doc.setFillColor(...peach);doc.rect(x0,infoY,labelNomeW,infoH,'F');doc.rect(x2,infoY,labelFuncW,infoH,'F');doc.rect(x0,infoY,fullW,infoH);[x1,x2,x3].forEach(x=>doc.line(x,infoY,x,infoY+infoH));doc.setFontSize(8.5);doc.text('NOME:',x0+5,infoY+21);doc.text('FUNÇÃO:',x2+5,infoY+21);const fit=(v:string,w:number)=>{let size=8.6;doc.setFontSize(size);while(size>6.2&&doc.getTextWidth(v)>w){size-=.2;doc.setFontSize(size)}return doc.splitTextToSize(v,w)[0]};doc.text(fit(l.collaborator_name.toUpperCase(),nomeW-10),x1+5,infoY+21);doc.text(fit((person?.role||'—').toUpperCase(),funcW-10),x3+5,infoY+21);
 const tableY=170,headH=32,xs=[left,left+34,left+fullW-86,left+fullW],widths=xs.slice(1).map((x,i)=>x-xs[i]);const rows=expenses.map(e=>{const desc=e.segment_number&&e.origin_city&&e.destination_city?`PASSAGEM RODOVIÁRIA - TRECHO ${e.segment_number} - ${e.origin_city}${e.origin_state?'/'+e.origin_state:''} > ${e.destination_city}${e.destination_state?'/'+e.destination_state:''}`:e.description.replace(/[→➜➡]/g,' > ').toUpperCase();const lines=doc.splitTextToSize(desc,widths[1]-10).slice(0,3);return{e,lines,height:lines.length===1?25:lines.length===2?36:47}});const bodyH=rows.reduce((n,x)=>n+x.height,0);doc.setFillColor(...peach);doc.rect(left,tableY,fullW,headH,'FD');doc.rect(left,tableY+headH,fullW,bodyH);for(let i=1;i<xs.length-1;i++)doc.line(xs[i],tableY,xs[i],tableY+headH+bodyH);doc.setFontSize(8.4);['ITEM','DESCRIÇÃO','VALOR'].forEach((h,i)=>doc.text(h,(xs[i]+xs[i+1])/2,tableY+20,{align:'center'}));doc.setFont('helvetica','normal');let y=tableY+headH;rows.forEach(({e,lines,height},i)=>{if(i)doc.line(left,y,left+fullW,y);const cy=y+height/2+3;doc.text(String(i+1).padStart(2,'0'),(xs[0]+xs[1])/2,cy,{align:'center'});doc.text(lines,xs[1]+5,cy-(lines.length-1)*5);doc.text('R$',xs[2]+5,cy);doc.text(money(e.amount),xs[3]-5,cy,{align:'right'});y+=height});doc.rect(xs[2],y,widths[2],28);doc.setFont('helvetica','bold');doc.text('R$',xs[2]+5,y+18);doc.text(money(expenses.reduce((n,e)=>n+Number(e.amount),0)),xs[3]-5,y+18,{align:'right'});if(returnBytes)return new Uint8Array(doc.output('arraybuffer'));doc.save(`folga_campo_${safe(l.collaborator_name)}_${l.competence.slice(0,7)}.pdf`)}

export async function suggestionReport(people:PrintPerson[],leaves:PrintLeave[],history:PrintHistory[],projectLabel:string,filters:{sectors:string[];months:string[]}){
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}),lines:{group:string;name:string;overdue:boolean;row:string[]}[]=[],pending:string[][]=[];
 for(const p of people){const status=(p.status||'').toUpperCase(),eligible=['S','SIM','TRUE','1'].includes((p.entitled_to_leave||'').toUpperCase())||['S','SIM','TRUE','1'].includes((p.uses_lodging||'').toUpperCase());if(['INATIVO','DESLIGADO','ABANDONO'].includes(status)||!eligible||(p.contract_type||'').toUpperCase().includes('PJ'))continue;const group=(p.department||p.team||p.sector||'SEM SETOR / EQUIPE').toUpperCase();if(!filters.sectors.includes(group))continue;const km=Number(p.distance_km||0);if(!km){pending.push([p.registration||'—',p.name.toUpperCase(),'SEM KM CADASTRADO']);continue}const r=rule(km);const prior=[...leaves.filter(l=>l.collaborator_id===p.id&&l.starts_on).map(l=>({start:l.starts_on!,end:l.ends_on||l.starts_on!,source:'FOLGA DE CAMPO'})),...history.filter(h=>h.collaborator_id===p.id&&h.starts_on).map(h=>({start:h.starts_on,end:h.ends_on||h.starts_on,source:h.source}))].sort((a,b)=>b.start.localeCompare(a.start))[0];const base=prior?.start||p.hired_on;if(!base){pending.push([p.registration||'—',p.name.toUpperCase(),'SEM ADMISSÃO / HISTÓRICO']);continue}const start=prior?addMonths(prior.start,r.months):fifth(base,r.months);if(!start){pending.push([p.registration||'—',p.name.toUpperCase(),'ERRO NO CÁLCULO']);continue}const overdue=start<today;if(!filters.months.includes(overdue?'ATRASADAS':start.slice(0,7)))continue;const end=prior?addMonths(prior.end,r.months):addDays(start,r.days-1);lines.push({group,name:p.name,overdue,row:[p.registration||'—',p.name.toUpperCase(),(p.role||'—').toUpperCase(),fmt(p.hired_on),`${p.travel_city||'—'} / ${p.travel_state||'—'}`,km.toLocaleString('pt-BR'),r.period,prior?.source||'ADMISSÃO',overdue?'ATRASADA':'PROGRAMADA',fmt(start),fmt(end),fmt(addDays(end,1)),'','']})}
 lines.sort((a,b)=>Number(b.overdue)-Number(a.overdue)||a.group.localeCompare(b.group,'pt-BR')||a.name.localeCompare(b.name,'pt-BR'));
 const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),W=doc.internal.pageSize.getWidth();const reportLogo=await logo();const header=()=>{doc.addImage(reportLogo,'PNG',12,8,35,17);doc.setTextColor(0);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text('RELATÓRIO DE SUGESTÃO DE BAIXADAS',W/2,15,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text(`${projectLabel} · ${filters.sectors.join(' | ')}`,W/2,21,{align:'center',maxWidth:W-40});doc.text(`Períodos: ${filters.months.join(' | ')} · Regra: data-base + ciclo exato (2/3/6 meses). Baixadas vencidas permanecem como ATRASADAS até novo registro real.`,W/2,26,{align:'center',maxWidth:W-25})};header();let y=31;const groups=[...new Set(lines.map(l=>l.group))];if(!lines.length){doc.setFontSize(11);doc.text('NENHUMA SUGESTÃO ENCONTRADA PARA OS FILTROS SELECIONADOS.',W/2,45,{align:'center'})}for(const [i,g] of groups.entries()){if(i&&y>155){doc.addPage();header();y=31}doc.setFillColor(235,235,235);doc.rect(6,y,W-12,7,'F');doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.text(g,8,y+4.8);y+=9;autoTable(doc,{startY:y,margin:{left:6,right:6,bottom:14},head:[['MAT.','COLABORADOR','FUNÇÃO','ADMISSÃO','CIDADE / UF','KM','PER.','BASE','SITUAÇÃO','INÍCIO','FIM','RETORNO','SAÍDA','RETORNO']],body:lines.filter(l=>l.group===g).map(l=>l.row),theme:'grid',styles:{font:'helvetica',fontSize:5.25,cellPadding:1.05,textColor:[20,20,20],lineColor:[90,90,90],lineWidth:.12,valign:'middle'},headStyles:{fontStyle:'bold',fillColor:[244,163,64],textColor:[0,0,0],halign:'center'},columnStyles:{0:{cellWidth:9,halign:'center'},1:{cellWidth:34},2:{cellWidth:31},3:{cellWidth:15,halign:'center'},4:{cellWidth:27},5:{cellWidth:10,halign:'center'},6:{cellWidth:10,halign:'center'},7:{cellWidth:24},8:{cellWidth:17,halign:'center'},9:{cellWidth:15,halign:'center'},10:{cellWidth:15,halign:'center'},11:{cellWidth:15,halign:'center'},12:{cellWidth:15},13:{cellWidth:15}},didParseCell:data=>{if(data.section==='body'&&data.column.index===8&&data.cell.raw==='ATRASADA')data.cell.styles.fontStyle='bold'}});y=(doc as jsPDF & {lastAutoTable:{finalY:number}}).lastAutoTable.finalY+6}if(pending.length){if(y>165){doc.addPage();header();y=31}doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('PENDÊNCIAS CADASTRAIS',8,y);autoTable(doc,{startY:y+3,margin:{left:8,right:8,bottom:14},head:[['MAT.','COLABORADOR','MOTIVO']],body:pending,theme:'grid',styles:{font:'helvetica',fontSize:7,cellPadding:1.8},headStyles:{fontStyle:'bold',fillColor:[230,230,230],textColor:[0,0,0]}})}for(let i=1;i<=doc.getNumberOfPages();i++){doc.setPage(i);doc.setFontSize(6.5);doc.setTextColor(90);doc.text(`Fonte: V2 · colaboradores + histórico real de Folga/Reembolso/Baixada · ${lines.length} sugestões · ${pending.length} pendências`,8,202);doc.text(`Página ${i}/${doc.getNumberOfPages()}`,W-8,202,{align:'right'})}doc.save(`RELATORIO_SUGESTAO_BAIXADAS_${today}.pdf`)
}
