'use client';
import {useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';

// Relação explícita: nenhum nome de tabela é aceito de parâmetros da página.
const tables=['cx_projects','cx_modules','cx_profiles','cx_memberships','cx_grants','cx_access_audit','cx_alert_settings','cx_cities','cx_closing','cx_collaborators','cx_contract_dashboard_settings','cx_contract_requests','cx_contracts','cx_employee_documents','cx_field_leave_competences','cx_field_leave_expenses','cx_field_leave_history','cx_field_leave_quote_files','cx_field_leaves','cx_housing','cx_portal_links','cx_reimbursement_competences','cx_reimbursement_receipts','cx_reimbursements','cx_user_shortcuts','cx_time_schedules','cx_time_periods','cx_time_entries','cx_time_entry_history','cx_time_signoffs'] as const;
export default function BackupManagement({sb}:{sb:SupabaseClient}){
 const supabaseProject=new URL(process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://supabase.com').hostname.split('.')[0];
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');
 async function exportData(){if(busy)return;setBusy(true);setError('');setProgress('Verificando o acesso…');
 try{const admin=await sb.rpc('cx_is_admin');if(admin.error||admin.data!==true)throw new Error('Somente o administrador pode exportar os dados.');
 const snapshot:Record<string,unknown[]>={};const counts:Record<string,number>={};for(const table of tables){setProgress(`Lendo ${table}…`);const all:unknown[]=[];for(let start=0;;start+=500){const {data, error:queryError}=await sb.from(table).select('*').range(start,start+499);if(queryError)throw new Error(`${table}: ${queryError.message}`);all.push(...(data||[]));if(!data||data.length<500)break;}snapshot[table]=all;counts[table]=all.length;}
 const stamp=new Date().toISOString();const content=JSON.stringify({format:'constru-x-v2-data-export',version:1,exported_at:stamp,scope:'public.cx_* (tabelas relacionadas na lista)',excludes:['auth.users e credenciais','arquivos binários do Storage','schemas privados','rotinas SQL e políticas RLS'],counts,tables:snapshot},null,2);
 const blob=new Blob([content],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`constru-x-v2-dados-${stamp.slice(0,10)}.json`;document.body.append(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),30000);setProgress(`Exportação concluída: ${Object.values(counts).reduce((a,b)=>a+b,0)} registros.`);
 }catch(e){setProgress('');setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <section className="cx-admin-backup"><div className="heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Backup</h1><p>Exporte os dados do Constru-X e consulte o backup integral do banco.</p></div></div><div className="panel"><h2>Exportação de dados do Constru-X</h2><p>Baixa um JSON com todas as linhas acessíveis ao administrador nas tabelas <code>public.cx_*</code>. O arquivo contém dados pessoais e deve ser guardado em local protegido.</p><button type="button" disabled={busy} onClick={()=>void exportData()}>{busy?'Gerando arquivo…':'⬇ EXPORTAR DADOS (JSON)'}</button>{progress&&<p role="status">{progress}</p>}{error&&<p role="alert" className="error">Exportação interrompida: {error}. Nenhum arquivo parcial foi baixado.</p>}<p className="cx-admin-help">Este arquivo serve para conferência e migração; não é uma restauração automática. Ele não contém usuários do Auth, senhas, arquivos do Storage nem a estrutura SQL do banco.</p></div><div className="panel"><h2>Backup integral do banco</h2><p>No Supabase, confira os backups disponíveis e as opções de restauração para o plano do projeto.</p><a className="cx-admin-external" href={`https://supabase.com/dashboard/project/${encodeURIComponent(supabaseProject)}/database/backups`} target="_blank" rel="noopener noreferrer">ABRIR BACKUPS NO SUPABASE ↗</a><p className="cx-admin-help">Backups do banco também não incluem o conteúdo dos arquivos do Storage. Salve esses arquivos separadamente.</p></div></section>;
}
