import {strToU8,zipSync} from 'fflate';

export type HousingRow={contract_code:string;description:string;supplier:string|null;monthly_cost:number;capacity:number;capacity_confirmed:boolean;status:string;measurement_start_day:number|null;lease_start:string|null;lease_end:string|null};
export type ContractRow={code:string;contract_type:string|null;starts_on:string|null;ends_on:string|null;supplier:string|null};
export type Resident={lodging:string|null;status:string|null;uses_lodging:string|null};
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]||char));
const xml=(value:string)=>strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+value);
const str=(ref:string,value:unknown,style:number)=>`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${esc(value)}</t></is></c>`;
const num=(ref:string,value:number|null,style:number)=>value==null||!Number.isFinite(value)?`<c r="${ref}" s="${style}"/>`:`<c r="${ref}" s="${style}"><v>${value}</v></c>`;
const serial=(value:string|null):number|null=>{if(!value||!/^\d{4}-\d\d-\d\d$/.test(value))return null;const d=new Date(`${value}T00:00:00Z`);return Number.isNaN(d.getTime())?null:(d.getTime()-Date.UTC(1899,11,30))/86400000;};
const br=(date:Date)=>`${String(date.getUTCDate()).padStart(2,'0')}/${String(date.getUTCMonth()+1).padStart(2,'0')}/${String(date.getUTCFullYear()).slice(-2)}`;
const dateFrom=(value:string)=>new Date(`${value}T00:00:00Z`);
function monthDate(year:number,month:number,day:number){return new Date(Date.UTC(year,month,Math.min(day,new Date(Date.UTC(year,month+1,0)).getUTCDate())));}
function measurementPeriod(day:number|null,weekEnd:Date):string{
 if(!day||day<1||day>31)return '';
 let start=monthDate(weekEnd.getUTCFullYear(),weekEnd.getUTCMonth(),day);
 if(start>weekEnd)start=monthDate(weekEnd.getUTCFullYear(),weekEnd.getUTCMonth()-1,day);
 let end=monthDate(start.getUTCFullYear(),start.getUTCMonth()+1,day);end=new Date(end.getTime()-86400000);
 return `${br(start)} à ${br(end)}`;
}
export function housingReportData(homes:HousingRow[],contracts:ContractRow[],residents:Resident[],referenceDate:string){
 const selected=dateFrom(referenceDate);if(Number.isNaN(selected.getTime()))throw new Error('Escolha uma data de referência válida.');
 const sunday=new Date(selected);sunday.setUTCDate(selected.getUTCDate()-selected.getUTCDay());
 const saturday=new Date(sunday);saturday.setUTCDate(sunday.getUTCDate()+6);
 const week=`Semana ${br(sunday).slice(0,5)} à ${br(saturday).slice(0,5)}`;
 const contractByCode=new Map(contracts.map(row=>[row.code.toUpperCase(),row]));
 const rows=homes.filter(row=>row.status==='ATIVO'&&!row.contract_code.toUpperCase().startsWith('OBRA-')).sort((a,b)=>a.contract_code.localeCompare(b.contract_code,'pt-BR')).map((home,index)=>{
  const linked=contractByCode.get(home.contract_code.toUpperCase());const start=home.lease_start||linked?.starts_on||null;const end=home.lease_end||linked?.ends_on||null;const day=home.measurement_start_day||Number(start?.slice(-2))||null;
  const occupied=residents.filter(person=>person.status==='ATIVO'&&person.uses_lodging==='SIM'&&person.lodging?.trim().toUpperCase()===home.contract_code.trim().toUpperCase()).length;
  return {number:index+1,contract:home.contract_code,status:'Ativo',supplier:home.supplier||linked?.supplier||'',start,end,measurement:measurementPeriod(day,saturday),amount:Number(home.monthly_cost||0),capacity:home.capacity_confirmed?home.capacity:null,occupied,team:home.description,week};
 });
 return {rows,week,total:rows.reduce((sum,row)=>sum+row.amount,0)};
}
export function createHousingReport(homes:HousingRow[],contracts:ContractRow[],residents:Resident[],projectCode:string,referenceDate:string,logo:Uint8Array):Uint8Array{
 const {rows:report,total}=housingReportData(homes,contracts,residents,referenceDate);
 const headers=['N','Contrato','Situação do CT - Ativo ou desmobilizado','Fornecedor*','Data de Início CT','Data de Término CT','Periodo da Medição','Valor Mensal','Capacidade de Alojados','Quantidade Alojados','Qual Equipe alojada ?'];
 let rows=`<row r="1" ht="36" customHeight="1">${str('C1',`OBRA ${projectCode} · CONTRATOS DE LOCAÇÃO DE IMÓVEIS`,7)}</row><row r="2" ht="34" customHeight="1">${str('C2',housingReportData(homes,contracts,residents,referenceDate).week,7)}</row><row r="3" ht="8" customHeight="1"/><row r="4" ht="70" customHeight="1">${headers.map((v,i)=>str(`${'ABCDEFGHIJK'[i]}4`,v,5)).join('')}</row>`;
 report.forEach((home,index)=>{const row=index+5;
 rows+=`<row r="${row}" ht="34" customHeight="1">${num(`A${row}`,home.number,0)}${str(`B${row}`,home.contract,1)}${str(`C${row}`,home.status,0)}${str(`D${row}`,home.supplier,1)}${num(`E${row}`,serial(home.start),2)}${num(`F${row}`,serial(home.end),2)}${str(`G${row}`,home.measurement,0)}${num(`H${row}`,home.amount,3)}${num(`I${row}`,home.capacity,4)}${num(`J${row}`,home.occupied,4)}${str(`K${row}`,home.team,1)}</row>`;
 });
 const last=report.length+4;const totalRow=last+1;
 rows+=`<row r="${totalRow}" ht="34" customHeight="1">${str(`A${totalRow}`,'Total',6)}${'BCDEFG'.split('').map(col=>`<c r="${col}${totalRow}" s="6"/>`).join('')}<c r="H${totalRow}" s="8"><f>${report.length?`SUM(H5:H${last})`:'0'}</f><v>${total.toFixed(2)}</v></c>${'IJK'.split('').map(col=>`<c r="${col}${totalRow}" s="6"/>`).join('')}</row>`;
 const merges=[`A1:B3`,`C1:K1`,`C2:K2`,`A${totalRow}:G${totalRow}`,`I${totalRow}:K${totalRow}`];
 const sheet=`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:K${totalRow}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="4" topLeftCell="A5" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="30"/><cols>${[8,20,24,48,19,20,31,20,20,21,75].map((width,i)=>`<col min="${i+1}" max="${i+1}" width="${width}" customWidth="1"/>`).join('')}</cols><sheetData>${rows}</sheetData><mergeCells count="${merges.length}">${merges.map(ref=>`<mergeCell ref="${ref}"/>`).join('')}</mergeCells><drawing xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:id="rId1"/><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="8" fitToWidth="1" fitToHeight="0"/></worksheet>`;
 const styles=`<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="2"><numFmt numFmtId="164" formatCode="dd/mm/yyyy"/><numFmt numFmtId="165" formatCode="&quot;R$&quot; #,##0.00"/></numFmts><fonts count="3"><font><sz val="12"/><name val="Calibri"/></font><font><b/><sz val="14"/><name val="Calibri"/><color rgb="FF2F261E"/></font><font><b/><sz val="13"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF6BE91"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"><color rgb="FFD6D9DD"/></left><right style="thin"><color rgb="FFD6D9DD"/></right><top style="thin"><color rgb="FFD6D9DD"/></top><bottom style="thin"><color rgb="FFD6D9DD"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="9"><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="left" vertical="center" wrapText="1"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="165" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment horizontal="right" vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="2" fillId="2" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="165" fontId="2" fillId="2" borderId="1" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment horizontal="right" vertical="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 const files:Record<string,Uint8Array>={
 '[Content_Types].xml':xml('<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/></Types>'),
 '_rels/.rels':xml('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'),
 'xl/workbook.xml':xml(`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${esc(`Obra ${projectCode}`.replace(/[\\/*?\[\]:]/g,'-').slice(0,31))}" sheetId="1" r:id="rId1"/></sheets><calcPr fullCalcOnLoad="1"/></workbook>`),
 'xl/_rels/workbook.xml.rels':xml('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'),
 'xl/styles.xml':xml(styles),'xl/worksheets/sheet1.xml':xml(sheet),
 'xl/worksheets/_rels/sheet1.xml.rels':xml('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>'),
 'xl/drawings/drawing1.xml':xml('<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><xdr:twoCellAnchor editAs="oneCell"><xdr:from><xdr:col>0</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>0</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:to><xdr:col>2</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>3</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="1" name="Logo CCL"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="rId1"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:twoCellAnchor></xdr:wsDr>'),
 'xl/drawings/_rels/drawing1.xml.rels':xml('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/ccl-logo.png"/></Relationships>'),
 'xl/media/ccl-logo.png':logo};
 return zipSync(files,{level:6});
}
