'use client';
import { useEffect,useMemo,useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
type Row={id:string;role:string;level_1_salary:number|null;level_2_salary:number|null;level_3_salary:number|null;active:boolean};
const money=(v:number|null)=>v==null?'—':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function JobSalary({sb,projectId,projectLabel,canEdit}:{sb:SupabaseClient;projectId:string;projectLabel:string;canEdit:boolean}){
 const [rows,setRows]=useState<Row[]>([]),[role,setRole]=useState(''),[s1,setS1]=useState(''),[s2,setS2]=useState(''),[s3,setS3]=useState(''),[edit,setEdit]=useState<string|null>(null),[msg,setMsg]=useState(''),[search,setSearch]=useState('');
 async function load(){const {data,error}=await sb.from('cx_job_salary_structure').select('id,role,level_1_salary,level_2_salary,level_3_salary,active').eq('project_id',projectId).order('role');setRows((data||[]) as Row[]);if(error)setMsg(error.message)}
 useEffect(()=>{void load()},[projectId]);
 const filteredRows=useMemo(()=>{const q=search.trim().toLocaleUpperCase('pt-BR');return q?rows.filter(r=>r.role.toLocaleUpperCase('pt-BR').includes(q)):rows},[rows,search]);
 function clear(){setRole('');setS1('');setS2('');setS3('');setEdit(null)}
 async function save(e:React.FormEvent){e.preventDefault();const payload={project_id:projectId,role:role.trim().toUpperCase(),level_1_salary:s1?Number(s1):null,level_2_salary:s2?Number(s2):null,level_3_salary:s3?Number(s3):null,active:true,updated_at:new Date().toISOString()};const q=edit?sb.from('cx_job_salary_structure').update(payload).eq('id',edit):sb.from('cx_job_salary_structure').insert(payload);const {error}=await q;if(error){setMsg(error.code==='23505'?'Este cargo já está cadastrado. Edite a mesma linha para informar os três níveis.':error.message);return}setMsg('Cargos e salários atualizados.');clear();await load()}
 return <section><div className="heading"><div><span className="eyebrow">DP/RH · {projectLabel}</span><h1>Cargos e Salários</h1><p>Uma única função por linha, com os três níveis salariais lado a lado.</p></div></div>{msg&&<div className="notice">{msg}</div>}{canEdit&&<form className="panel cx-job-form" onSubmit={save}><label>Função / Cargo<input required value={role} onChange={e=>setRole(e.target.value.toUpperCase())}/></label><label>Nível 1<input type="number" min="0" step="0.01" value={s1} onChange={e=>setS1(e.target.value)}/></label><label>Nível 2<input type="number" min="0" step="0.01" value={s2} onChange={e=>setS2(e.target.value)}/></label><label>Nível 3<input type="number" min="0" step="0.01" value={s3} onChange={e=>setS3(e.target.value)}/></label><button className="cx-primary">{edit?'SALVAR ALTERAÇÕES':'+ CADASTRAR CARGO'}</button>{edit&&<button type="button" onClick={clear}>CANCELAR</button>}</form>}<div className="panel cx-job-search"><label>Pesquisar cargo / função<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="DIGITE O CARGO OU FUNÇÃO" /></label><span>{filteredRows.length} de {rows.length} cargo(s)</span></div><div className="panel cx-job-table"><table><thead><tr><th>FUNÇÃO / CARGO</th><th>NÍVEL 1</th><th>NÍVEL 2</th><th>NÍVEL 3</th>{canEdit&&<th>AÇÕES</th>}</tr></thead><tbody>{filteredRows.map(r=><tr key={r.id}><td><strong>{r.role}</strong></td><td>{money(r.level_1_salary)}</td><td>{money(r.level_2_salary)}</td><td>{money(r.level_3_salary)}</td>{canEdit&&<td><button type="button" onClick={()=>{setEdit(r.id);setRole(r.role);setS1(r.level_1_salary?.toString()||'');setS2(r.level_2_salary?.toString()||'');setS3(r.level_3_salary?.toString()||'')}}>✏️ EDITAR</button></td>}</tr>)}</tbody></table></div></section>
}
