'use client';
import { useEffect,useMemo,useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

type Sector={id:string;name:string;active:boolean};
type Team={id:string;sector_id:string;name:string;active:boolean};
type Colab={id:string;registration:string|null;name:string;role:string|null;department:string|null;sector:string|null;sector_id:string|null;team_id:string|null;hired_on:string|null;status:string|null;foreman:string|null};
const norm=(v?:string|null)=>(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[m]||m));
function experience(hired?:string|null){if(!hired)return '—';const d=new Date(hired+'T12:00:00');if(Number.isNaN(+d))return '—';const end=new Date(d);end.setDate(end.getDate()+90);const now=new Date();if(now<=end){const days=Math.max(0,Math.ceil((+end-+now)/86400000));return `EM EXPERIÊNCIA · ${days}D`;}return 'EFETIVADO';}
export default function Organization({sb,projectId,projectLabel,canEdit}:{sb:SupabaseClient;projectId:string;projectLabel:string;canEdit:boolean}){
 const [sectors,setSectors]=useState<Sector[]>([]),[teams,setTeams]=useState<Team[]>([]),[cols,setCols]=useState<Colab[]>([]),[sector,setSector]=useState(''),[team,setTeam]=useState(''),[sectorId,setSectorId]=useState(''),[msg,setMsg]=useState('');
 const [filterTeam,setFilterTeam]=useState(''),[filterRole,setFilterRole]=useState('');
 async function load(){const [a,b,c]=await Promise.all([sb.from('cx_sectors').select('id,name,active').eq('project_id',projectId).eq('active',true).order('name'),sb.from('cx_teams').select('id,sector_id,name,active').eq('project_id',projectId).eq('active',true).order('name'),sb.from('cx_collaborators').select('id,registration,name,role,department,sector,sector_id,team_id,hired_on,status,foreman').eq('project_id',projectId).eq('status','ATIVO').order('name')]);setSectors((a.data||[]) as Sector[]);setTeams((b.data||[]) as Team[]);setCols((c.data||[]) as Colab[]);if(a.error||b.error||c.error)setMsg(a.error?.message||b.error?.message||c.error?.message||'Erro')}
 useEffect(()=>{void load()},[projectId]);
 const sectorMap=useMemo(()=>new Map(sectors.map(x=>[x.id,x.name])),[sectors]); const teamMap=useMemo(()=>new Map(teams.map(x=>[x.id,x.name])),[teams]);
 const teamOptions=useMemo(()=>teams.map(t=>({id:t.id,label:`${sectorMap.get(t.sector_id)||''} / ${t.name}`})).sort((a,b)=>a.label.localeCompare(b.label)),[teams,sectorMap]);
 const roles=useMemo(()=>Array.from(new Set(cols.map(c=>c.role?.trim()).filter(Boolean) as string[])).sort((a,b)=>a.localeCompare(b)),[cols]);
 const members=useMemo(()=>cols.filter(c=>(!filterTeam||c.team_id===filterTeam)&&(!filterRole||norm(c.role)===norm(filterRole))),[cols,filterTeam,filterRole]);
 const cargoCounts=useMemo(()=>{const m=new Map<string,number>();members.forEach(c=>{const k=(c.role||'SEM FUNÇÃO').trim();m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));},[members]);
 const teamCounts=useMemo(()=>{const m=new Map<string,number>();members.forEach(c=>{const k=teamMap.get(c.team_id||'')||c.department||'NÃO INFORMADO';m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]);},[members,teamMap]);
 const inExp=members.filter(c=>experience(c.hired_on).startsWith('EM ')).length; const avg=teamCounts.length?members.length/teamCounts.length:0;
 const row=(c:Colab)=>[c.registration||'',c.name,c.role||'',teamMap.get(c.team_id||'')||c.department||'',sectorMap.get(c.sector_id||'')||c.sector||'',experience(c.hired_on)];
 async function addSector(){if(!sector.trim())return;const {error}=await sb.from('cx_sectors').insert({project_id:projectId,name:sector.trim().toUpperCase(),active:true});if(error)setMsg(error.code==='23505'?'Setor já cadastrado.':error.message);else{setSector('');setMsg('Setor cadastrado.');await load()}}
 async function addTeam(){if(!sectorId||!team.trim())return;const {error}=await sb.from('cx_teams').insert({project_id:projectId,sector_id:sectorId,name:team.trim().toUpperCase(),active:true});if(error)setMsg(error.code==='23505'?'Equipe já cadastrada neste setor.':error.message);else{setTeam('');setMsg('Equipe cadastrada.');await load()}}
 function reportFilter(){return [filterTeam?`Setor/Equipe: ${teamOptions.find(x=>x.id===filterTeam)?.label}`:'',filterRole?`Cargo: ${filterRole}`:''].filter(Boolean).join(' · ')||'Todos os setores (nenhum filtro aplicado)'}
 function exportPdf(){const doc=new jsPDF({orientation:'landscape',unit:'pt',format:'a4'});const w=doc.internal.pageSize.getWidth();doc.setFillColor(20,21,23);doc.rect(0,0,w,60,'F');doc.setTextColor(245,197,24);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Organograma Setor/Equipe — Relatório',30,27);doc.setTextColor(230);doc.setFont('helvetica','normal');doc.setFontSize(9.5);doc.text(`Construtora Centro Leste · ${projectLabel}`,30,44);doc.setTextColor(20);doc.setFontSize(10);doc.text(`Filtro aplicado: ${reportFilter()}`,30,78);doc.text(`Total de colaboradores: ${members.length}    |    Gerado em: ${new Date().toLocaleString('pt-BR')}`,30,93);autoTable(doc,{startY:110,head:[['Mat.','Nome','Função','Equipe','Setor','Experiência']],body:members.map(row),styles:{fontSize:8.5,cellPadding:4},headStyles:{fillColor:[31,56,100],textColor:255},alternateRowStyles:{fillColor:[245,245,245]},margin:{left:30,right:30}});doc.save(`organograma_setor_equipe_${new Date().toISOString().slice(0,10)}.pdf`)}
 function exportXls(){const data=[['Organograma Setor/Equipe — Relatório'],[`Construtora Centro Leste · ${projectLabel}`],[],['Filtro aplicado',reportFilter()],['Total de colaboradores',members.length],['Gerado em',new Date().toLocaleString('pt-BR')],[],['Por Cargo'],['Cargo','Quantidade'],...cargoCounts,[],['Colaboradores'],['Matrícula','Nome','Função','Equipe','Setor','Experiência'],...members.map(row)];const html=`<html><head><meta charset="utf-8"></head><body><table>${data.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</table></body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff',html],{type:'application/vnd.ms-excel'}));a.download=`organograma_setor_equipe_${new Date().toISOString().slice(0,10)}.xls`;a.click();URL.revokeObjectURL(a.href)}
 function exportVisual(){if(!filterTeam&&!filterRole){setMsg('Selecione um filtro de Setor/Equipe ou Cargo antes de gerar o organograma visual.');return}if(!members.length){setMsg('Nenhum colaborador encontrado com o filtro atual.');return}const doc=new jsPDF({orientation:'portrait',unit:'pt',format:'a4'}),w=doc.internal.pageSize.getWidth(),h=doc.internal.pageSize.getHeight(),M=30;doc.setFillColor(20,21,23);doc.rect(0,0,w,60,'F');doc.setTextColor(245,197,24);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Organograma — Setor/Equipe',30,27);doc.setTextColor(230);doc.setFont('helvetica','normal');doc.setFontSize(9.5);doc.text(`Construtora Centro Leste · ${projectLabel}`,30,44);let y=92;const root=filterTeam?teamOptions.find(x=>x.id===filterTeam)?.label||'SETOR/EQUIPE':`Cargo: ${filterRole}`;doc.setFillColor(230,240,251);doc.setDrawColor(24,95,165);doc.roundedRect(30,y,260,55,6,6,'FD');doc.setTextColor(12,68,124);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(doc.splitTextToSize(root,235),160,y+20,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(`${members.length} colaborador(es)`,160,y+44,{align:'center'});y+=90;for(const [cargo,count] of cargoCounts){const names=members.filter(c=>(c.role||'SEM FUNÇÃO').trim()===cargo).map(c=>c.name);const boxH=42+names.length*12;if(y+boxH>h-35){doc.addPage();y=55}doc.setFillColor(224,242,235);doc.setDrawColor(15,110,86);doc.roundedRect(80,y,w-110,36,5,5,'FD');doc.setTextColor(8,80,65);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(`${cargo} · ${count} pessoa(s)`,w/2+25,y+22,{align:'center'});doc.setTextColor(50);doc.setFont('helvetica','normal');doc.setFontSize(8.5);let ny=y+51;names.forEach(n=>{doc.text(n,90,ny,{maxWidth:w-130});ny+=12});y+=boxH+18}doc.save(`organograma_visual_setor_equipe_${new Date().toISOString().slice(0,10)}.pdf`)}
 return <section><div className="heading"><div><span className="eyebrow">DP/RH · {projectLabel}</span><h1>Organograma Setor/Equipe</h1><p>Estrutura organizacional por setor/equipe (encarregado responsável).</p></div></div>{msg&&<div className="notice">{msg}<button onClick={()=>setMsg('')}>×</button></div>}
 <div className="metrics cx-org-kpis"><article className="metric"><span>COLABORADORES</span><strong>{members.length}</strong></article><article className="metric"><span>SETORES/EQUIPES</span><strong>{teamCounts.length}</strong></article><article className="metric"><span>CARGOS/FUNÇÕES</span><strong>{cargoCounts.length}</strong></article><article className="metric"><span>MAIOR SETOR/EQUIPE</span><strong>{teamCounts[0]?.[1]||0}</strong></article><article className="metric"><span>EM EXPERIÊNCIA</span><strong>{inExp}</strong></article><article className="metric"><span>MÉDIA POR SETOR</span><strong>{avg.toFixed(1)}</strong></article></div>
 <div className="panel cx-org-report-filters"><select value={filterTeam} onChange={e=>setFilterTeam(e.target.value)}><option value="">TODOS OS SETORES/EQUIPES</option>{teamOptions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select value={filterRole} onChange={e=>setFilterRole(e.target.value)}><option value="">TODOS OS CARGOS</option>{roles.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>{setFilterTeam('');setFilterRole('')}}>LIMPAR FILTRO</button><button onClick={exportPdf}>📄 EXPORTAR PDF</button><button onClick={exportXls}>📊 EXPORTAR XLS</button><button onClick={exportVisual}>🌳 EXPORTAR ORGANOGRAMA (PDF)</button></div>
 <div className="panel cx-org-members"><div className="panel-head"><div><h2>Colaboradores</h2><p>{members.length} colaborador(es){!filterTeam&&!filterRole?' — todos os ativos':''}</p></div></div><div className="table-scroll"><table><thead><tr><th>MAT.</th><th>NOME</th><th>FUNÇÃO</th><th>EQUIPE</th><th>SETOR</th><th>EXPERIÊNCIA</th></tr></thead><tbody>{members.map(c=><tr key={c.id}><td>{c.registration}</td><td><strong>{c.name}</strong></td><td>{c.role}</td><td>{teamMap.get(c.team_id||'')||c.department}</td><td>{sectorMap.get(c.sector_id||'')||c.sector}</td><td>{experience(c.hired_on)}</td></tr>)}</tbody></table></div></div>
 {canEdit&&<details className="panel cx-org-maint"><summary>CADASTRO DE SETORES E EQUIPES</summary><div className="cx-org-page-form"><label>Novo setor<input value={sector} onChange={e=>setSector(e.target.value.toUpperCase())}/><button type="button" onClick={()=>void addSector()}>+ CADASTRAR SETOR</button></label><label>Setor<select value={sectorId} onChange={e=>setSectorId(e.target.value)}><option value="">SELECIONE</option>{sectors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Nova equipe<input value={team} onChange={e=>setTeam(e.target.value.toUpperCase())}/><button type="button" disabled={!sectorId} onClick={()=>void addTeam()}>+ CADASTRAR EQUIPE</button></label></div></details>}
 </section>
}
