'use client';
import { useEffect,useMemo,useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
type Sector={id:string;name:string;active:boolean}; type Team={id:string;sector_id:string;name:string;active:boolean};
export default function Organization({sb,projectId,projectLabel,canEdit}:{sb:SupabaseClient;projectId:string;projectLabel:string;canEdit:boolean}){
 const [sectors,setSectors]=useState<Sector[]>([]),[teams,setTeams]=useState<Team[]>([]),[sector,setSector]=useState(''),[team,setTeam]=useState(''),[sectorId,setSectorId]=useState(''),[msg,setMsg]=useState('');
 async function load(){const [a,b]=await Promise.all([sb.from('cx_sectors').select('id,name,active').eq('project_id',projectId).order('name'),sb.from('cx_teams').select('id,sector_id,name,active').eq('project_id',projectId).order('name')]);setSectors((a.data||[]) as Sector[]);setTeams((b.data||[]) as Team[]);if(a.error||b.error)setMsg(a.error?.message||b.error?.message||'Erro')}
 useEffect(()=>{void load()},[projectId]); const grouped=useMemo(()=>sectors.map(s=>({...s,teams:teams.filter(t=>t.sector_id===s.id)})),[sectors,teams]);
 async function addSector(){if(!sector.trim())return;const {error}=await sb.from('cx_sectors').insert({project_id:projectId,name:sector.trim().toUpperCase(),active:true});if(error)setMsg(error.code==='23505'?'Setor já cadastrado.':error.message);else{setSector('');setMsg('Setor cadastrado.');await load()}}
 async function addTeam(){if(!sectorId||!team.trim())return;const {error}=await sb.from('cx_teams').insert({project_id:projectId,sector_id:sectorId,name:team.trim().toUpperCase(),active:true});if(error)setMsg(error.code==='23505'?'Equipe já cadastrada neste setor.':error.message);else{setTeam('');setMsg('Equipe cadastrada.');await load()}}
 return <section><div className="heading"><div><span className="eyebrow">DP/RH · {projectLabel}</span><h1>Organograma · Setores e Equipes</h1><p>Estrutura organizacional utilizada no cadastro dos colaboradores.</p></div></div>{msg&&<div className="notice">{msg}</div>}{canEdit&&<div className="panel cx-org-page-form"><label>Novo setor<input value={sector} onChange={e=>setSector(e.target.value.toUpperCase())}/><button type="button" onClick={()=>void addSector()}>+ CADASTRAR SETOR</button></label><label>Setor<select value={sectorId} onChange={e=>setSectorId(e.target.value)}><option value="">SELECIONE</option>{sectors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Nova equipe<input value={team} onChange={e=>setTeam(e.target.value.toUpperCase())}/><button type="button" disabled={!sectorId} onClick={()=>void addTeam()}>+ CADASTRAR EQUIPE</button></label></div>}<div className="cx-org-cards">{grouped.map(s=><article className="panel" key={s.id}><h2>{s.name}</h2><div>{s.teams.length?s.teams.map(t=><span className="cx-org-team" key={t.id}>{t.name}</span>):<small>SEM EQUIPES CADASTRADAS</small>}</div></article>)}</div></section>
}
